#Print ბრძანება 20-ჯერ გამოიყენეთ და დაბეჭდეთ თქვენთვის სასურველი ინფორმაცია

print("1. I have just started learning at goa")
print("2. Now i'm level 2")
print("3. I just did my sololearn homework ")
print("4. my first name is")
print("5. ერეკლე ")
print("6. and my surname is")
print("7. ნაპირელი")
print("And I'm 13 years old")
print("8. python is a powerful programming laguage ")
print("9. It also is one of the easiest programming languages to understand ")
print("10. It is widely used")
print("11. It's very beginner friendly language")
print("12. There's also library called turtle in which you can draw things")
print("13. The first thing I drew in turtle was a house")
print("14. after this homework I am going to try and draw a big castle ")
print("15. Then get a few friends")
print("16. ...")
print("17. ...")
print("18. ...")
print("19. ...")
print("20. ...")

